### PR TITLE
Use go-libp2p-http

### PR DESCRIPTION
**Pull request by hsanjuan**
License: MIT
Signed-off-by: Hector Sanjuan <hector@protocol.ai>

### CODE REVIEW

**Comment by hsanjuan** [comment]
not tested though

**Comment by ianopolous** [comment]
Thank you! This looks great. However I tested it with the same url I was testing the other pr with and get the following on the daemon console (I can't see the error in the code though):
http: proxy error: input isn't valid multihash
For reference the url I'm using is: 
http://localhost:5001/proxy/http/QmfC6jinsXgpqqNpiTc8v9KH6DJjCVi9z2b3bzMqTub5wM/test/

**Comment by hsanjuan** [comment]
@ianopolous I just pushed something that seems to fix it for me

**Comment by ianopolous** [comment]
Thanks @hsanjuan . I just tried it out and now I get:

http: proxy error: protocol not supported

Which I guess is the /x issue.

**Comment by hsanjuan** [comment]
@ianopolous yeah, this works for me well using `allow-custom-protocol` flag on the p2p listen side.

Right now: `curl -v -X GET localhost:5001/proxy/http/Qmc4jCXpz292LaPEMmbue4aQxWSwKNgcXXDgurLKYt7UA5/test/id` on one side

and `ipfs --api /ip4/127.0.0.1/tcp/6001 p2p listen --allow-custom-protocol test /ip4/127.0.0.1/tcp/1234` on the other correctly forwards things to the local webserver on `:1234`.

I had made a mistake with the proxy url path that I just fixed.

**Comment by ianopolous** [comment]
@hsanjuan I've just tried this out, and the request makes it to the final server, but with the wrong path. The path seen at the destination is:
http/QmdbxQmnvjVtquy8NFHP1ukidLW468FWuqEUTmDjgwPJQv/test/

**Comment by hsanjuan** [comment]
@ianopolous sorry, I forgot to push the fix yesterday

**Review by ianopolous — APPROVED** [review]
This works now. Excellent!

**Pull request merged**
